# Configuration file for Otchkies.

pipeline:

  input_stream:
    name: realsense #C:\Users\jinr2.STUDENT\data\data_1.bag #realsense #webcam # /Users/jaime/Desktop/SwinDRLVP-staging/RealSense-videos-swin/20210303_162650.bag
    #archival_dir: C:\Users\jinr2.STUDENT\data

  module_chain:

    - name: Calibration_Threshold
      path: /Users/jaime/Documents/SwinDRLVP/otchkies
      implementation: vision_processing.basic.Calibration_Threshold
      kwargs:
        intensity: 0
        all_white: False


  output_streams:
#    - name: web
    - name: voice
#    - name: brainport
    - name: window
